### ISSUE TITLE
Unknown field _poke

### ISSUE THREAD

**Issue by jesusbagpuss** [eprintsug/hefce_oa#19]
Error in log file - looks like it's caused by this:
https://github.com/eprintsug/hefce_oa/blob/master/lib/cfg.d/hefce_oa_triggers.pl#L43-L56

I haven't started to trace it yet, but it looks like it might be preventing some commits happening - and therefore isn't good!

```
DBD::mysql::st execute failed: Unknown column '_poke' in 'field list' at /usr/share/eprints/perl_lib/EPrints/Database.pm line 1184.
[wrro] UPDATE `eprint` SET `_poke`=?, `hoa_compliant`=?, `hoa_date_foa_year`=?, `hoa_date_foa_month`=?, `hoa_date_foa_day`=? WHERE `eprintid`='89693': 1054 at /usr/share/eprints/perl_lib/EPrints/Database.pm line 1590
[wrro]  EPrints::Database::update('EPrints::Database::mysql=HASH(0x7f9f5caa8060)', 'EPrints::DataSet=HASH(0x7f9f59f92700)', 'HASH(0x7f9f5cf467d0)', 'HASH(0x7f9f5cfd1b30)') called at /usr/share/eprints/perl_lib/EPrints/DataObj.pm line 652
[wrro]  EPrints::DataObj::commit('EPrints::DataObj::EPrint=HASH(0x7f9f5cf784d0)', undef) called at /usr/share/eprints/perl_lib/EPrints/DataObj/EPrint.pm line 1011
[wrro]  EPrints::DataObj::EPrint::commit('EPrints::DataObj::EPrint=HASH(0x7f9f5cf784d0)', undef) called at /usr/share/eprints/perl_lib/EPrints/DataObj/Document.pm line 1243
[wrro]  EPrints::DataObj::Document::commit('EPrints::DataObj::Document=HASH(0x7f9f5cf842d0)') called at /usr/share/eprints/perl_lib/EPrints/Plugin/InputForm/Component/Documents.pm line 68
[wrro]  EPrints::Plugin::InputForm::Component::Documents::update_from_form('EPrints::Plugin::InputForm::Component::Documents=HASH(0x7f9f5...', 'EPrints::ScreenProcessor=HASH(0x7f9f5ca61a80)') called at /usr/share/eprints/perl_lib/EPrints/Workflow/Stage.pm line 218
[wrro]  EPrints::Workflow::Stage::update_from_form('EPrints::Workflow::Stage=HASH(0x7f9f5cf8ece0)', 'EPrints::ScreenProcessor=HASH(0x7f9f5ca61a80)') called at /usr/share/eprints/perl_lib/EPrints/Workflow.pm line 398
[wrro]  EPrints::Workflow::update_from_form('EPrints::Workflow=HASH(0x7f9f5ceeca70)', 'EPrints::ScreenProcessor=HASH(0x7f9f5ca61a80)', 'notes') called at /usr/share/eprints/perl_lib/EPrints/Plugin/Screen/EPrint/Edit.pm line 94
[wrro]  EPrints::Plugin::Screen::EPrint::Edit::from('EPrints::Plugin::Screen::EPrint::Edit=HASH(0x7f9f5cee2810)') called at /usr/share/eprints/perl_lib/EPrints/ScreenProcessor.pm line 310
[wrro]  EPrints::ScreenProcessor::process('EPrints::ScreenProcessor', 'session', 'EPrints::Repository=HASH(0x7f9f53a68518)', 'template', undef, 'url', '/cgi/users/home') called at /usr/share/eprints/cgi/users/home line 40
[wrro]  ModPerl::ROOT::ModPerl::Registry::usr_share_eprints_cgi_users_home::handler('Apache2::RequestRec=SCALAR(0x7f9f5cf87120)') called at /usr/lib64/perl5/ModPerl/RegistryCooker.pm line 204
[wrro]  eval {...} called at /usr/lib64/perl5/ModPerl/RegistryCooker.pm line 204
[wrro]  ModPerl::RegistryCooker::run('ModPerl::Registry=HASH(0x7f9f5cf0bd40)') called at /usr/lib64/perl5/ModPerl/RegistryCooker.pm line 170
[wrro]  ModPerl::RegistryCooker::default_handler('ModPerl::Registry=HASH(0x7f9f5cf0bd40)') called at /usr/lib64/perl5/ModPerl/Registry.pm line 31
[wrro]  ModPerl::Registry::handler('ModPerl::Registry', 'Apache2::RequestRec=SCALAR(0x7f9f5cf87120)') called at -e line 0
[wrro]  eval {...} called at -e line 0
```

**Comment by jesusbagpuss** [comment]
Observed in 3.3.10. 
To reproduce:
1. EPrint in live archive
2. Document security='public'
3. Update document metadata (watch error logs at the same time).

This

``` perl
$doc->parent->{changed}->{_poke}++;
```

seems to be a bit of a hack - to get the parent to run commit triggers?
Is there a 'normal' method to get the parent to recommit in this situation (I'm guessing a 'force' cause other things to happen that we might not want)?

Would copying one of the hefce_oa fields into the changed hash be better?

**Comment by jesusbagpuss** [comment]
When checking fields, the reference to '_poke' will hit this:
https://github.com/eprints/eprints/blob/3.3/perl_lib/EPrints/DataSet.pm#L683-L690
- returning a 'longtext' field.

A call to $dataobj->update will ignore this (https://github.com/eprints/eprints/blob/3.3/perl_lib/EPrints/DataObj.pm#L541) but a call to $dataobj->commit (https://github.com/eprints/eprints/blob/3.3/perl_lib/EPrints/DataObj.pm#L633) doesn't.

I'm not sure what the 'magic' fields refer to - something starting with an underscore that should be ignored (or at least not added to the database)?

This sounds like it might be a bug in core EPrints - but one that we'll have to deal with properly here (as it'll be installed on many EPrints versions).

**Comment by drtjmb** [comment]
The eprint triggers do the work to determine date of first compliance, date of first open access and run the compliance tests.

The triggers get called whenever the eprint is changed.

However a change to a document can also influence the compliance status of an eprint - so we need the eprint triggers to also be run when a document is changed. Under normal circumstances this does not happen:

DataObj::Document::commit() does call commit() on the parent eprint https://github.com/eprints/eprints/blob/3.3/perl_lib/EPrints/DataObj/Document.pm#L1239-L1244 but without $force=1, DataObj::EPrint::commit() will terminate early https://github.com/eprints/eprints/blob/3.3/perl_lib/EPrints/DataObj/EPrint.pm#L984-L988 without running any eprint triggers https://github.com/eprints/eprints/blob/3.3/perl_lib/EPrints/DataObj/EPrint.pm#L1014

So setting $docs->parent->{changed}->{_poke} is a hack to stop the eprint commit() terminating early and gives the triggers a chance to run and update the compliance status of the eprint.

I wasn't aware of the implications of using "_poke" - suggest we just define a "hoa_flag" field to use for this purpose.
