### ISSUE TITLE
Explodes when things are created before 1900

### ISSUE THREAD

**Issue by patrickmcsweeney** [eprintsug/hefce_oa#35]
The code uses Time::Piece->strptime in quite a few places. If it gets handed a date earlier than 1900 it explodes quite unceremoniously. This really breaks anything in the repository which has a date earlier than 1900. You cant edit it or even call ->commit on the eprint.

My two suggested solutions are:
- do something to check for year earlier than 1900 and skip it (nothing that old is going to be ref relevent anyway)
- stop using Time::Piece and instead use DateTime::Format::HTTP and DateTime

**Comment by wfyson** [comment]
Taken the path of not setting the date fields if the date is before 1900 - https://github.com/eprints/hefce_oa/commit/54816352379387e1ec5a9b2ff2aaf48968468388
