### ISSUE TITLE
Item with embargo period marked as OA compliant  

### ISSUE THREAD

**Issue by ghost** [eprintsug/hefce_oa#41]
Hi All,

I noticed a potential issue that I thought would be a good idea to share with you.

If an embargo period is added to an already deposited OA compliant item, this item will remain compliant while being on embargo. In other words, the embargo period, if added in a second moment, does not affect the compliance status of the item.

While the plugin is working as expected - that is, it's taking into consideration the date of the first compliant Open Access - I think that this might lead to unwanted outcomes in some cases. 

We thought that a potential solution may be adding a condition that makes sure that if an item has an active embargo period, then it cannot be compliant.

**Comment by cziaarm** [comment]
fixed a while back with e92aeace57d75b84ae358ecab2443456096278dd
