### ISSUE TITLE
v1.3 is broken in multi-archive setup

### ISSUE THREAD

**Issue by jesusbagpuss** [eprintsug/hefce_oa#42]
Reference of field 'hoa_exclude' breaks archives where this plugin is not installed.

Breaks upload of documents / edit of eprints.

**Comment by jesusbagpuss** [comment]
There's been a few updates to this and other packages in the past that break multi-archive configurations.

Might be worth adding a unit test for it (not sure if that's possible though!).

**Comment by wfyson** [comment]
Thanks for alerting me to this @jesusbagpuss - I'll have a look into other multi-archive issues as soon as possible.

**Comment by jesusbagpuss** [comment]
This was the only multi-archive issue on here.
I should add the comment above to the main EPrints repo.

I did try making a new epm / epmi for this change, but the checksums of all xml files were also changed - which didn't seem right (not quite sure what was going on there).

**Comment by wfyson** [comment]
I've just updated the epm and epmi so hopefully everything should be lined up now.
