### ISSUE TITLE
New exception: Apr2018 deposit on pub not accept

### ISSUE THREAD

**Issue by jesusbagpuss** [eprintsug/hefce_oa#44]
New deposit exception for items deposited after 1st April 2018:
"The output was not deposited within three months of acceptance date, but was deposited within three months of the earliest date of publication."

Taken from: http://www.ref.ac.uk/media/ref,2021/downloads/REF%202017_04%20Decisions.pdf

> 38.    The funding bodies have carefully considered the evidence gathered in the survey 
> relating to the policy’s deposit requirements. We wish to continue building on the progress 
> achieved to date and to maintain the momentum towards developing new tools to 
> implement deposit as soon after the point of acceptance as possible. We therefore confirm 
> the implementation of the REF OA policy as previously set out. The policy will require
> outputs to be deposited as soon after the point of acceptance as possible, and no later 
> than three months after this date (as given in the acceptance letter or email from the 
> publication to the author) from 1 April 2018. 
> 
> 39.    Taking account of some of the practical concerns raised through the survey in relation 
> to deposit on acceptance, we will introduce a deposit exception in to the policy from 
> 1 April 2018. This exception will allow outputs unable to meet this deposit timescale, to 
> remain compliant if they are deposited up to three months after the date of publication. 
> The exception will read: ‘The output was not deposited within three months of acceptance 
> date, but was deposited within three months of the earliest date of publication.’ This 
> exception will remain in place for the rest of the REF 2021 publication period.

**Comment by wfyson** [comment]
Hi @jesusbagpuss - thanks for raising the issue here. I've just applied commit https://github.com/eprintsug/hefce_oa/commit/082525bccda446e02e06258bb72fbd20256fe1e6 to add the new exception. Am I right in thinking that is all that is required here?
