### ISSUE TITLE
published date and rioxx2 integration

### ISSUE THREAD

**Issue by cziaarm** [eprintsug/hefce_oa#46]
Here's a fun one.

https://github.com/eprintsug/hefce_oa/blob/master/lib/cfg.d/hefce_oa_integration.pl#L61-L64

means that hefce_oa will use the rioxx2_publication_date if it is available (ie it has been overriden in favour of whatever is in the more traditional publication date. Something similar happens for the accepted date, however the rioxx2_publication_date is a freetext field (and defined as such by the rioxx... or at least the snippet that comes with the rioxx plugin).

So fill it out with an incomplete date or indeed any date that is not YYYY-MM-DD will cause the hefce_oa plugin obvious issues...

I guess a suggestion would be to test that any date coming at hefce_oa from rioxx2 is YYYY-MM-DD and act accordingly...?

Cheers,

Rory

**Comment by wfyson** [comment]
I've added a regex to check we have a valid date format from RIOXX with commit https://github.com/eprints/hefce_oa/commit/54816352379387e1ec5a9b2ff2aaf48968468388
